FROM mcr.microsoft.com/dotnet/core/sdk:5.0-nanoserver-ltsc2022 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet publish IoTEdgeDeployBlobs.Module -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:5.0-nanoserver-ltsc2022
WORKDIR /app
COPY --from=build-env /app/out ./

#create a blob folder where the blob will be stored!
RUN mkdir blobs

ENTRYPOINT ["dotnet", "IoTEdgeDeployBlobs.Module.dll"]