name: Build image, push & deploy

on:
  workflow_dispatch:
  push:
    paths:
    - 'source/**'

env:
  ACR_NAME: acrtodosample               # set the name for the Azure Container Registry
  ACR_LOGIN_SERVER: acrtodosample.azurecr.io # fqdn for the Azure Container Registry
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }} # user name for accessing Azure Container Registry
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }} # password for accesing the Azure Container Registry
  LOG_ANALYTICS_SHARED_KEY: ${{ secrets.LOG_ANALYTICS_SHARED_KEY }}
  DEPLOY_BLOBS_MODULE_NAME: "DeployBlobsModule"
  MODULE_CONTAINER_IMAGE_NAME: "deployblobs"
  ROOT_VERSION: "1.0.0"
  VERSION: "${{ env.ROOT_VERSION }}.${{ env.GITHUB_RUN_NUMBER }}" #SIMPLE VERSIONING
  FILE_VERSION: "${{ env.VERSION }}"
  ASSEMBLY_VERSION: "${{ env.VERSION }}"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64", "amd64-debug"]

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v2

    - name: Prepare Version
      run: |


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ env.ACR_LOGIN_SERVER }}
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}
        logout: false
    

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: ./source/IoTEdgeDeployBlobs.Module
        push: true
        tags: ${{ env.ACR_LOGIN_SERVER }}/${{ env.MODULE_CONTAINER_IMAGE_NAME }}:${{ env.VERSION }}-${{ matrix.arch }}
        file: ./source/IoTEdgeDeployBlobs.Module/Dockerfile.amd64
        build-args: |
          VERSION=${{ env.VERSION }}-${{ matrix.arch }}
          FILE_VERSION=${{ env.FILE_VERSION }}
          ASSEMBLY_VERSION=${{ env.ASSEMBLY_FILE_VERSION }}


  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v2

    - name: Login for az cli commands 
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: IoT Edge Deployment
      run: |
        echo az command

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples